name: BackEnd

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Build with JDK${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      working-directory: ./backend
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./backend
      run: ./gradlew build
